### ISSUE TITLE
Bridge Dropping

### ISSUE THREAD

**Issue by maroshu** [CyrilPeponnet/smartthings#3]
Hello, I've been using Reconnect for a while and it has worked great.  A couple small issues that I've run into such as when renaming a scene, it never seems to make its way over, but nothing major until now.  About 3 days ago reconnect forgot my Hue hub.  The only remedy I could find was to uninstall Reconnect (which unfortunately means removing every light/scene from all of my routines and such) and reinstall.  So I did that and went through and re-added all of the lights and scenes into routines, etc.  It worked well for about 24 hours, but it has once again dropped the Hue hub.  Any advice?

**Comment by jpiazza1971** [comment]
I had the exact same problem, and just did the removal/reinstall.  Hope it sticks...

**Comment by maroshu** [comment]
Mine has been good the last few days after the 2nd removal/reinstall.  Wonder if it has anything to do with maybe the ip address changing or something like that?  Perhaps setting up a static ip for the hue bridge could prevent it?

**Comment by CyrilPeponnet** [comment]
We rely on SmartThings hub for this. Could be another bug on their side. I didn't notice anything on my own
